language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
branches:
  only:
  - master
  - gh-pages
env:
  global:
    secure: 3UCwexrXTzUP5q8ABgGHjRM015O7SDb0SuqC/qLhSWMbbgAjj5hXHbpD7rL4fLxn9own1tz/uz0lC5ZwjYAd40T7eAQdPRFNB3KvxIMHGW5RfXh5XdfiA3aVGQIc/zA//gHFIGTbnb5zpiJdY7avsSJ+UfCswIATKbXLwexYOU5CGIKdaFjBcSGCJ5E9ghwK14dRTyn5M6Zfgm6T1xYTK3sri7NHyAKjlkVTE6Cp3xsYdkUd2vuxBFM6zNnNmPZWYIJxEzVd2lWf1oQooktgQfby0CuiLAJjTfqiG0ShmfTrS4XwnxkKkSChEypxmn/dgTkNUxKrRkG1WfRqqg1SmldRjc+yn5PhFgtm2KPGvtUnhVluBZmztq6BVWWqDsqm2VL/w8OnXDS6tIeW2R0BFsL01rP9/IV/bJT9C2i61P/+o4bg3a2ZdT9gzm9kCvssWLn2wsENdXf3ye4BauLJVbd5eZwUyqMdr6t1Ltfy/GWuwRNzQ487hfXi8iqmfhdpXjpw5HwHBWbWJ4p/vh2VRDH2B+PJR5PGWdsMNeFmEGajOvFp1FOU2LxxLNHuboPXSfOD38lWrAycSZrNClxk3oMI7f9JgUM/NfplCWAy3xuIcY1MaP3jJ2VSJI+G4rqMJ4xikAyl/fmj1N3Qb1WrfHSEFEeKCDNtr4P3w1skkFo=
