---

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_script:
- gem install ascii_binder
- git config credential.helper "/bin/bash $PWD/credential-helper.sh"

script:
  - make build
  - make test

deploy:
  provider: script
  script: make publish-github
  on:
    branch: master
